[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tree_sitter_type_provider"
version = "2.1.7"
description = "Type providers for tree-sitter in Python"
requires-python = ">=3.9"
keywords = ["type-provider"]
authors = [{ name = "Wen Kokke" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Compilers",
]
dependencies = ["tree-sitter ==0.20.0", "dataclasses-json >=0.5.7, <0.6"]

[project.optional-dependencies]
dev = ["build >=0.8.0, <0.9", "twine >=4.0.1, <5"]
test = ["pytest >=7.1.2, <8", "pytest-golden >=0.2.2, <0.3"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
repository = "https://github.com/wenkokke/py-tree-sitter-type-provider"

[tool.setuptools.package-data]
tree_sitter_type_provider = ["py.typed"]

[pytest]
testpaths = "tests"

[tool.pytest.ini_options]
enable_assertion_pass_hook = true
filterwarnings = ["ignore::DeprecationWarning:.*:"]

[tool.bumpver]
current_version = "2.1.7"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py39,py310
isolated_build = True

[testenv]
deps =
  pytest >=7.1.2, <8
  pytest-golden >=0.2.2, <0.3
commands = pytest
"""
