[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tree_sitter_type_provider"
version = "2.1.8"
description = "Type providers for tree-sitter in Python."
license = "MIT"
authors = ["Wen Kokke <wenkokke@users.noreply.github.com>"]
readme = "README.md"
repository = "https://github.com/wenkokke/py-tree-sitter-type-provider"
keywords = ["parsing", "tree-sitter", "type-provider"]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Topic :: Software Development :: Compilers",
]

[tool.poetry.dependencies]
python = "^3.9"
tree-sitter = "^0.20.0"
dataclasses-json = "^0.5.7"

[tool.poetry.group.test]
[tool.poetry.group.test.dependencies]
pytest = "^7.1.2"
pytest-golden = "^0.2.2"

[tool.pytest.ini_options]
enable_assertion_pass_hook = true
filterwarnings = ["ignore::DeprecationWarning:.*:"]
testpaths = "tests"

[tool.mypy]
python_version = 3.9
namespace_packages = true
explicit_package_bases = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true

[tool.bumpver]
current_version = "2.1.8"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py39,py310
isolated_build = True

[testenv]
deps =
  pytest==7.1.2
  pytest-golden==0.2.2
commands = pytest
"""
