name: "Setup Python"
description: "Setup Python"
inputs:
  python-version:
    required: false
    description: "Version of Python to use."
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v7

    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}-
