name: build

on:
  push:
    branches:
      - dev
    tags:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os }} / Python ${{ matrix.python-version[0] }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - ["3.7", "py37"]
          - ["3.8", "py38"]
          - ["3.9", "py39"]
          - ["3.10", "py310"]
          - ["3.11", "py311"]
        experimental: [false]
        include:
          - # Earliest supported version:
            os: ubuntu-20.04
            python-version: ["3.7.1", "py37"]
            experimental: false

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version[0] }}

      - name: Build & Test
        run: |
          tox run -e ${{ matrix.python-version[1] }}

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release.yml
