name: CI

on: [push]

defaults:
  run:
    shell: bash

env:
  RECOMMENDED_OS: "Linux"
  RECOMMENDED_PYTHON_VERSION: "3.9"

jobs:
  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      ################################################################################
      # Setup
      ################################################################################
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
            requirements-test.txt
            requirements.txt
      - run: pip install .[dev,test]
      ################################################################################
      # Test
      ################################################################################
      - name: Run PyTest
        run: pytest

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      ################################################################################
      # Setup
      ################################################################################
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.RECOMMENDED_PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
            requirements-test.txt
            requirements.txt
      - run: pip install .[dev,test]
      ################################################################################
      # Build
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        run: python -m build

      ################################################################################
      # Publish to PyPi
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        run: |
          twine check dist/*
          twine upload --skip-existing -r pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      ################################################################################
      # Publish to GitHub Release
      ################################################################################
      - if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
          fail_on_unmatched_files: true
